/* Generated By:JavaCC: Do not edit this line. ParserGramaticaConstants.java */
package com.esvux.CompiladorGramatica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserGramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int DEC = 29;
  /** RegularExpression Id. */
  int CHAR = 30;
  /** RegularExpression Id. */
  int STR = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\";\"",
    "\"Terminal\"",
    "\"as\"",
    "\"int\"",
    "\"char\"",
    "\"double\"",
    "\"string\"",
    "\"bool\"",
    "\"NoTerminal\"",
    "\"RegistrarPrecedencia\"",
    "\"(\"",
    "\",\"",
    "\"Asociatividad.izq\"",
    "\"Asociatividad.der\"",
    "\")\"",
    "\"Raiz\"",
    "\"=\"",
    "\".Regla\"",
    "\"|\"",
    "\"+\"",
    "\"<::\"",
    "\"::>\"",
    "<ID>",
    "<INT>",
    "<DEC>",
    "<CHAR>",
    "<STR>",
  };

}
