/* Generated By:JavaCC: Do not edit this line. ParserGramaticaConstants.java */
package com.esvux.CompiladorGramatica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserGramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RSLT = 50;
  /** RegularExpression Id. */
  int PYC = 51;
  /** RegularExpression Id. */
  int ID = 52;
  /** RegularExpression Id. */
  int CHAR = 53;
  /** RegularExpression Id. */
  int STR = 54;
  /** RegularExpression Id. */
  int INT = 55;
  /** RegularExpression Id. */
  int DEC = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"Terminal\"",
    "\"as\"",
    "\"int\"",
    "\"char\"",
    "\"double\"",
    "\"string\"",
    "\"bool\"",
    "\"NoTerminal\"",
    "\"RegistrarPrecedencia\"",
    "\"(\"",
    "\",\"",
    "\"Asociatividad.izq\"",
    "\"Asociatividad.der\"",
    "\")\"",
    "\"Raiz\"",
    "\"=\"",
    "\".Regla\"",
    "\"|\"",
    "\"+\"",
    "\"<::\"",
    "\"::>\"",
    "\"Write\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"Or\"",
    "\"Xor\"",
    "\"And\"",
    "\"Not\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
    "\"true\"",
    "\"false\"",
    "<RSLT>",
    "\";\"",
    "<ID>",
    "<CHAR>",
    "<STR>",
    "<INT>",
    "<DEC>",
  };

}
